unpackaged/main/default/objects/Shipping__c/Shipping__c.object-meta.xml
<CustomObject>
    <label>Shipping</label>
    <nameField>
        <displayFormat>S{YY}{MM}{DD}{0000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shippings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Shipping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account related to the Shipping order</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shippings</relationshipLabel>
    <relationshipName>Shippings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Delivery_Street__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Street__c</fullName>
    <label>Delivery Street</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sender</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <infoMessage>Please be sure that an Account has Contact related</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shippings</relationshipLabel>
    <relationshipName>Shippings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>false</active>
    <label>Test</label>
</RecordType>

unpackaged/main/default/classes/ShippingControllerTest.cls
@isTest
class ShippingControllerTest {
    public static List<Shipping__c> createDummyShippingRecords(Integer numShips){
        List<Shipping__c> shp = new List<Shipping__c>();
        Account account = new Account(Name = 'OwO');
        insert account;
        //Account__c, Sender__c]: [Account__c, Sender__c
        Contact contact = new Contact(LastName = 'Senior uwu',
                                     AccountId = account.Id);
        insert contact;
        for (Integer count = 0; count < numShips; count++) {
        	Shipping__c s = new Shipping__c(Account__c=account.Id, Delivery_Street__c='Str. '+count,
                                           Sender__c = contact.Id
                                           );
            shp.add(s);
    	}
        
        insert shp;
        
        return shp;
    }
    
    //Exception Expected
    @isTest
    static void testGetShippingInformation (){
    	List<Shipping__c> dummyShippings = createDummyShippingRecords(5); 
    	Test.startTest();
        try
      {
          List<Shipping__c> result = ShippingController.getShippingInformation('String que no pertenece a ningun record');
      }
      catch(exception e)
         {
			}     
    	Test.stopTest();
}
    
    //Result Expected
    @isTest
    static void testGetShippingInformation2 (){
        List<Shipping__c> dummyShippings = createDummyShippingRecords(5);
        Id searchId = dummyShippings.get(1).Id;
        Shipping__c searchShipping = [SELECT Name FROM Shipping__c WHERE Id = :searchId];
        String trackNum = searchShipping.Name;
        Test.startTest();
        List<Shipping__c> result = ShippingController.getShippingInformation(trackNum);
        Integer actualSize = result.size();
    	Test.stopTest();
        System.assertEquals(dummyShippings.isEmpty(), false);
    }
}