unpackaged/main/default/objects/Shipping__c/Shipping__c.object-meta.xml
<CustomObject>
    <label>Shipping</label>
    <nameField>
        <displayFormat>S{YY}{MM}{DD}{0000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shippings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Trac__c/Trac__c.object-meta.xml
<CustomObject>
    <label>Tracking</label>
    <nameField>
        <displayFormat>T{YY}{MM}{DD}{0000}</displayFormat>
        <label>Tracking Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Trac__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Trac__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Trac__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Trac__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <label>Shipping</label>
    <referenceTo>Shipping__c</referenceTo>
    <relationshipLabel>Trackings</relationshipLabel>
    <relationshipName>Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/TrackingController.cls
public with sharing class TrackingController {
    @AuraEnabled(cacheable=true)
    public static List<Trac__c> getTrackingInformation(String trackingNumber) {
        List<Trac__c> trackingInfo = new List<Trac__c>();
        trackingInfo = [SELECT Id, City__c, Country_Code__c, Description__c FROM Trac__c WHERE Shipping__r.Name =: trackingNumber ORDER BY CreatedDate DESC];
    
        return trackingInfo;
    }
}