unpackaged/main/default/objects/Shipping__c/Shipping__c.object-meta.xml
<CustomObject>
    <label>Shipping</label>
    <nameField>
        <displayFormat>S{YY}{MM}{DD}{0000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shippings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Shipping__c/fields/Delivery_City__c.field-meta.xml
<CustomField>
    <fullName>Delivery_City__c</fullName>
    <label>Delivery City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Delivery_Country__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Country__c</fullName>
    <label>Delivery Country</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Return_City__c.field-meta.xml
<CustomField>
    <fullName>Return_City__c</fullName>
    <label>Return City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Return_Country__c.field-meta.xml
<CustomField>
    <fullName>Return_Country__c</fullName>
    <label>Return Country</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Preparing to Ship</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Received on destination country</fullName>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Out for delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ShippingController.cls
public without sharing class ShippingController {
    @AuraEnabled(cacheable=true)
    public static List<Shipping__c> getShippingInformation(String trackingNumber) {
        List<Shipping__c> shippingInfo = new List<Shipping__c>();
        shippingInfo = [SELECT Id, Name, Return_City__c, Return_Country__c, Delivery_City__c, Delivery_Country__c, Status__c FROM Shipping__c WHERE Name = :trackingNumber];
    
        if(shippingInfo.size() == 0){
            throw new AuraHandledException('No Record Found.'); 
        }
    
        return shippingInfo;
    }
}