unpackaged/main/default/objects/Shipping__c/Shipping__c.object-meta.xml
<CustomObject>
    <label>Shipping</label>
    <nameField>
        <displayFormat>S{YY}{MM}{DD}{0000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shippings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Trac__c/Trac__c.object-meta.xml
<CustomObject>
    <label>Tracking</label>
    <nameField>
        <displayFormat>T{YY}{MM}{DD}{0000}</displayFormat>
        <label>Tracking Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Trac__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <label>Shipping</label>
    <referenceTo>Shipping__c</referenceTo>
    <relationshipLabel>Trackings</relationshipLabel>
    <relationshipName>Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/TrackingLocationController.cls
public without sharing class TrackingLocationController {
    @AuraEnabled(Cacheable=true)
    public static Trac__c[] getAllTracks( String search){
        return [
            SELECT
                Name,
                Location__Latitude__s,
                Location__Longitude__s
                FROM Trac__c
                WHERE Shipping__r.Name =: search
                ORDER BY Name
                LIMIT 50
        ];
    } 
}