unpackaged/main/default/objects/Account/fields/CustomerPriority__c.field-meta.xml
<CustomField>
    <fullName>CustomerPriority__c</fullName>
    <label>Customer Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Shipping__c/Shipping__c.object-meta.xml
<CustomObject>
    <label>Shipping</label>
    <nameField>
        <displayFormat>S{YY}{MM}{DD}{0000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shippings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Shipping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account related to the Shipping order</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shippings</relationshipLabel>
    <relationshipName>Shippings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Delivery_City__c.field-meta.xml
<CustomField>
    <fullName>Delivery_City__c</fullName>
    <label>Delivery City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Delivery_Country__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Country__c</fullName>
    <label>Delivery Country</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Delivery_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Postal_Code__c</fullName>
    <label>Delivery Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Delivery_State__c.field-meta.xml
<CustomField>
    <fullName>Delivery_State__c</fullName>
    <label>Delivery State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Delivery_Street__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Street__c</fullName>
    <label>Delivery Street</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sender</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <infoMessage>Please be sure that an Account has Contact related</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shippings</relationshipLabel>
    <relationshipName>Shippings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Preparing to Ship</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Received on destination country</fullName>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Out for delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Shipping__c/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>false</active>
    <label>Test</label>
</RecordType>

unpackaged/main/default/objects/Trac__c/Trac__c.object-meta.xml
<CustomObject>
    <label>Tracking</label>
    <nameField>
        <displayFormat>T{YY}{MM}{DD}{0000}</displayFormat>
        <label>Tracking Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Trac__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Trac__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <label>Shipping</label>
    <referenceTo>Shipping__c</referenceTo>
    <relationshipLabel>Trackings</relationshipLabel>
    <relationshipName>Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/TrackingTriggerHandlerTest.cls
@isTest
public class TrackingTriggerHandlerTest {
    @isTest static void testSettingLongitudeLatitude(){
        Account Acc = new Account();
        Acc.Name='Account Business Low';
        Acc.CustomerPriority__c='Low';
        Acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        
        insert Acc;
        
        Contact cont = new Contact();
        cont.Salutation='Mr';
        cont.LastName='Test';
        cont.AccountId = Acc.Id;
        cont.Email = 'Test_Test@gmail.com';
        
        insert cont;
        
        Shipping__c shipp = new Shipping__c();
        shipp.Account__c = Acc.Id;
        shipp.Sender__c = cont.Id;
        shipp.Status__c = 'Processing';
        shipp.Delivery_Street__c ='test';
        shipp.Delivery_Postal_Code__c='test';
        shipp.Delivery_City__c='test';
        shipp.Delivery_State__c='test';
        shipp.Delivery_Country__c='test';
        
        insert shipp;
        
        Trac__c trac = new Trac__c();
        trac.Description__c = 'test';
        trac.Shipping__c = shipp.Id;
         
        insert trac;
        
        System.assert(trac.Location__Latitude__s != null && trac.Location__Longitude__s != null);
        
        
    }
}