unpackaged/main/default/objects/Case/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tracking Number</label>
    <referenceTo>Shipping__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/Shipping__c.object-meta.xml
<CustomObject>
    <label>Shipping</label>
    <nameField>
        <displayFormat>S{YY}{MM}{DD}{0000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shippings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Shipping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account related to the Shipping order</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shippings</relationshipLabel>
    <relationshipName>Shippings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Shipping__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Preparing to Ship</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Received on destination country</fullName>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Out for delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Trac__c/Trac__c.object-meta.xml
<CustomObject>
    <label>Tracking</label>
    <nameField>
        <displayFormat>T{YY}{MM}{DD}{0000}</displayFormat>
        <label>Tracking Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Trac__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <label>Shipping</label>
    <referenceTo>Shipping__c</referenceTo>
    <relationshipLabel>Trackings</relationshipLabel>
    <relationshipName>Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/trackHandler.cls
public with sharing class trackHandler {

    @AuraEnabled
    public static void deleteTrackingRecord(Id recordId ){
        try {
            Trac__c trackToDelete = [SELECT Id FROM Trac__c WHERE Id = :recordId LIMIT 1]; 
            delete trackToDelete;
        } catch (DmlException e) {
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<getWrapper> getTracking(String trackingNumber){
        String searchkey = '%' + trackingNumber + '%';
        List<Trac__c> tracs =  [SELECT Name, Shipping__r.Account__r.Name, Shipping__r.Account__r.RecordType.Name, 
        Shipping__r.Account__r.CustomerPriority__c, Shipping__r.Account__r.Shipments_this_Month__c, status__c  
        FROM Trac__c WHERE Name LIKE: searchkey LIMIT 5];
        List<Case> cases = [SELECT RecordType.Name, Tracking_Number__c FROM Case WHERE Tracking_Number__c != null];
        return wrapTrackingContent(tracs,cases);
    }

    @AuraEnabled(cacheable=true)
    public static List<getWrapper> getAllTracking(String trackingNumber){
        String searchkey = '%' + trackingNumber + '%';
        List<Trac__c> tracs =  [SELECT Name, Shipping__r.Account__r.Name, Shipping__r.Account__r.RecordType.Name, 
        Shipping__r.Account__r.CustomerPriority__c, Shipping__r.Account__r.Shipments_this_Month__c, status__c  
        FROM Trac__c WHERE Name LIKE: searchkey];
        List<Case> cases = [SELECT RecordType.Name, Tracking_Number__c FROM Case WHERE Tracking_Number__c != null];
        return wrapTrackingContent(tracs,cases);
    }

    private static List<getWrapper> wrapTrackingContent(List<Trac__c> tracs, List<Case> cases){
        Map<Id, Case> casesMapped = new Map<Id, Case>();
        for(Case thiscase : cases){
            casesMapped.put(thiscase.Tracking_Number__c, thiscase);
        }
        List<getWrapper> wrapperList = new List<getWrapper>();
        for(Trac__c trac: tracs){
            getWrapper wrapper = new getWrapper();
            wrapper.Id = trac.Id;
            wrapper.trackingNumber = trac.Name;
            wrapper.customerName = trac.Shipping__r.Account__r.Name;
            wrapper.customerType = trac.Shipping__r.Account__r.RecordType.Name;
            if(casesMapped.containsKey(trac.Id)){
                wrapper.caseType = casesMapped.get(trac.Id).RecordType.Name;
            }
            wrapper.customerPriority = trac.Shipping__r.Account__r.CustomerPriority__c;
            wrapper.shipmentsThisMonth = Integer.valueOf(trac.Shipping__r.Account__r.Shipments_this_Month__c);
            wrapper.status = trac.status__c;
            wrapperList.add(wrapper);
        }
        return wrapperList;
    }

    public class getWrapper {
        @AuraEnabled public Id Id;
        @AuraEnabled public String trackingNumber;
        @AuraEnabled public String customerName;
        @AuraEnabled public String customerType;
        @AuraEnabled public String caseType;
        @AuraEnabled public String customerPriority;
        @AuraEnabled public Integer shipmentsThisMonth; 
        @AuraEnabled public String status;
    }
}